### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by YoussefSaghbini**
Some templates to use to describe the feature/bug in a clean format

### CODE REVIEW

**Comment by YoussefSaghbini** [comment]
This is not needed, duplicate issue

**Review by MuneebNasir — COMMENTED** [review]
This Bug Report Required for each new Issue ?

**Comment by YoussefSaghbini** [comment]
Made a duplicate PR and wanted to see if any actions occurred with labelling an issue with 'duplicate'

**Comment by YoussefSaghbini** [comment]
Duplicate of #20

**Pull request closed without merging**
