### PR TITLE
Added Author JPA tests

### PR DESCRIPTION
**Pull request by vanarman**
Testing 
- Author getters
- Author setters

### CODE REVIEW

**Review by MuneebNasir — APPROVED** [review]
Looks Good

**Review by decarbonite — COMMENTED** [review]
I don't think testing getters and setters are necessary at all. Unless the getters and setters actually contain logic that could be tested.

**Comment by vanarman** [comment]
> I don't think testing getters and setters are necessary at all. Unless the getters and setters actually contain logic that could be tested.

I agree but I guess we can keep it for now.

**Review by vanarman — COMMENTED** [review]
I agree but I guess we can keep it for now.

**Review by MuneebNasir — APPROVED** [review]
Good for ensuring code coverage

**Comment by YoussefSaghbini** [comment]
The file has already been moved to master and this pull request is redundant

**Pull request closed without merging**
